-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 03:12:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema demo_data
-- -----------------------------------------------------
-- a

-- -----------------------------------------------------
-- Schema demo_data
--
-- a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo_data` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `demo_data` ;

-- -----------------------------------------------------
-- Table `demo_data`.`docent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`docent` (
  `iddocent` VARCHAR(45) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iddocent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo_data`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `demo_data`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`student` (
  `studentennummer` INT(9) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`studentennummer`),
  UNIQUE INDEX `studentennummer_UNIQUE` (`studentennummer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo_data`.`klas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`klas` (
  `idklas` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idklas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo_data`.`inschrijving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`inschrijving` (
  `idinschrijving` INT NOT NULL,
  `student` INT NOT NULL,
  `klas` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idinschrijving`),
  INDEX `studentennummer_idx` (`student` ASC) VISIBLE,
  INDEX `idklas_idx` (`klas` ASC) VISIBLE,
  CONSTRAINT `studentennummer`
    FOREIGN KEY (`student`)
    REFERENCES `demo_data`.`student` (`studentennummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idklas`
    FOREIGN KEY (`klas`)
    REFERENCES `demo_data`.`klas` (`idklas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo_data`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`meeting` (
  `idmeeting` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `datum` DATETIME(6) NOT NULL,
  `locatie` VARCHAR(45) NOT NULL,
  `organisator` VARCHAR(45) NOT NULL,
  `deelnemer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmeeting`),
  INDEX `idklas_idx` (`deelnemer` ASC) VISIBLE,
  INDEX `iddocent_idx` (`organisator` ASC) VISIBLE,
  UNIQUE INDEX `datum_UNIQUE` (`datum` ASC) VISIBLE,
  CONSTRAINT `iddocent`
    FOREIGN KEY (`organisator`)
    REFERENCES `demo_data`.`docent` (`iddocent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idklas`
    FOREIGN KEY (`deelnemer`)
    REFERENCES `demo_data`.`klas` (`idklas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo_data`.`gesprek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`gesprek` (
  `idgesprek` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `datum` DATETIME(6) NOT NULL,
  `locatie` VARCHAR(45) NOT NULL,
  `organisator` VARCHAR(45) NOT NULL,
  `deelnemer` INT NOT NULL,
  PRIMARY KEY (`idgesprek`),
  INDEX `iddocent_idx` (`organisator` ASC) VISIBLE,
  INDEX `studentennummer_idx` (`deelnemer` ASC) VISIBLE,
  UNIQUE INDEX `datum_UNIQUE` (`datum` ASC) VISIBLE,
  CONSTRAINT `iddocent`
    FOREIGN KEY (`organisator`)
    REFERENCES `demo_data`.`docent` (`iddocent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `studentennummer`
    FOREIGN KEY (`deelnemer`)
    REFERENCES `demo_data`.`student` (`studentennummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo_data`.`aanwezigheid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_data`.`aanwezigheid` (
  `idaanwezigheid` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idaanwezigheid`),
  CONSTRAINT `studentennummer`
    FOREIGN KEY (`idaanwezigheid`)
    REFERENCES `demo_data`.`student` (`studentennummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idmeeting`
    FOREIGN KEY (`idaanwezigheid`)
    REFERENCES `demo_data`.`meeting` (`idmeeting`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
